/** Product-owned terminal atlas. Runtime font slot policy stays unchanged. */
import { readFileSync, writeFileSync } from "node:fs";
import opentype from "opentype.js";
import { bakeSlot } from "../vendor/pocketjs/framework/compiler/bake-font.ts";
import { TERM_GLYPHS } from "../shared/protocol.ts";
import { TERM_FONT_SLOT } from "../shared/layout.ts";
import { bitmapCell } from "../shared/bitmap-font.ts";
import { FONT_SOURCES, loadBitmapFont, type TerminalFontName } from "../shared/font-sources.ts";

// Unicode box-drawing arm masks (N/E/S/W) and stroke weights.
const BOX_SHAPES = [26, 42, 21, 37, 26, 42, 21, 37, 27, 43, 21, 37, 22, 38, 38, 38, 28, 44, 44, 44, 19, 35, 35, 35, 25, 41, 41, 41, 23, 39, 39, 39, 39, 39, 39, 39, 29, 45, 45, 45, 45, 45, 45, 45, 30, 46, 46, 46, 46, 46, 46, 46, 27, 43, 43, 43, 43, 43, 43, 43, 31, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 26, 42, 21, 37, 58, 53, 54, 54, 54, 60, 60, 60, 51, 51, 51, 57, 57, 57, 55, 55, 55, 61, 61, 61, 62, 62, 62, 59, 59, 59, 63, 63, 63, 22, 28, 25, 19, 27, 27, 16, 24, 17, 18, 20, 40, 33, 34, 36, 42, 37, 42, 37];

export function terminalFont(face: TerminalFontName = "spleentt"): Uint8Array {
  const bitmap = loadBitmapFont(face);
  const fallback = loadBitmapFont("fusion");
  const source = readFileSync(new URL("../vendor/pocketjs/assets/fonts/JetBrainsMono-Regular.ttf", import.meta.url));
  const font = opentype.parse(source.buffer.slice(source.byteOffset, source.byteOffset + source.byteLength) as ArrayBuffer);
  const chars = [...new Set([...Array.from({ length: 95 }, (_, n) => n + 32), ...[...TERM_GLYPHS].map(ch => ch.codePointAt(0)!)])].sort((a, b) => a - b);
  const baked = bakeSlot(font, TERM_FONT_SLOT, 8, false, chars);
  const n = baked.glyphCount, cmapEnd = 16 + n * 8;
  const bytes = new Uint8Array(cmapEnd + n * 50);
  bytes.set(baked.bytes.subarray(0, cmapEnd));
  bytes[8] = 5; bytes[9] = 10; bytes[10] = 7; bytes[11] = 10;
  const view = new DataView(bytes.buffer);
  for (let i = 0; i < n; i++) {
    const at = 16 + i * 8, cp = view.getUint32(at, true), gid = view.getUint16(at + 4, true);
    bytes[at + 6] = 5; bytes[at + 7] = 0;
    const pixels = bitmapCell(bitmap, cp) ?? bitmapCell(fallback, cp);
    for (let y = 0; y < 10; y++) for (let x = 0; x < 5; x++) {
      const outline = baked.bytes[cmapEnd + gid * baked.cellW * baked.cellH + (y + 1) * baked.cellW + x] ?? 0;
      bytes[cmapEnd + gid * 50 + y * 5 + x] = pixels ? pixels[y * 5 + x] : outline >= 96 ? 255 : 0;
    }
    // Terminal furniture joins at cell edges, including all four arms of
    // a junction. Font line metrics cannot supply these 5 x 10 boundaries.
    if (cp >= 0x2500 && cp <= 0x257f) {
      const shape = BOX_SHAPES[cp - 0x2500], arms = shape & 15, weight = shape >> 4;
      for (let y = 0; y < 10; y++) for (let x = 0; x < 5; x++) {
        const vertical = weight === 3 ? x === 1 || x === 3 : x === 2 || weight === 2 && x === 3;
        const horizontal = weight === 3 ? y === 3 || y === 5 : y === 4 || weight === 2 && y === 5;
        let ink = !!((arms & 1) && y <= 4 && vertical || (arms & 4) && y >= 4 && vertical ||
          (arms & 8) && x <= 2 && horizontal || (arms & 2) && x >= 2 && horizontal);
        if (cp >= 0x2571 && cp <= 0x2573) ink = (cp !== 0x2572 && x === 4 - Math.round(y * 4 / 9)) || (cp !== 0x2571 && x === Math.round(y * 4 / 9));
        bytes[cmapEnd + gid * 50 + y * 5 + x] = ink ? 255 : 0;
      }
    }
    if (cp >= 0x2580 && cp <= 0x259f) {
      const quadrants = [4, 8, 1, 13, 9, 7, 11, 2, 6, 14];
      for (let y = 0; y < 10; y++) for (let x = 0; x < 5; x++) {
        let ink = cp === 0x2580 ? y < 5 : cp <= 0x2588 ? y >= 10 - Math.round((cp - 0x2580) * 10 / 8) :
          cp <= 0x258f ? x < Math.round((0x2590 - cp) * 5 / 8) : cp === 0x2590 ? x >= 3 :
          cp === 0x2591 ? (x + 2 * y) % 4 === 0 : cp === 0x2592 ? (x + y) % 2 === 0 :
          cp === 0x2593 ? (x + 2 * y) % 4 !== 0 : cp === 0x2594 ? y === 0 : cp === 0x2595 ? x === 4 :
          !!(quadrants[cp - 0x2596] & (y < 5 ? (x < 3 ? 1 : 2) : (x < 3 ? 4 : 8)));
        bytes[cmapEnd + gid * 50 + y * 5 + x] = ink ? 255 : 0;
      }
    }
  }
  return bytes;
}

if (import.meta.main) {
  const faces = Object.fromEntries(Object.keys(FONT_SOURCES).map(name => [name, Buffer.from(terminalFont(name as TerminalFontName)).toString("base64")]));
  const text = `// Generated by bun scripts/font.ts. See assets/fonts/README.md.\nexport const TERM_FONTS = ${JSON.stringify(faces)};\nexport const TERM_FONT = TERM_FONTS.spleentt;\n`;
  const path = new URL("../app/font.generated.ts", import.meta.url);
  if (process.argv.includes("--check")) {
    if (readFileSync(path, "utf8") !== text) throw new Error("Terminal font is stale");
  } else writeFileSync(path, text);
}
